### ISSUE TITLE
Request for `NewClient` to return interface

### ISSUE THREAD

**Issue by cholick** [cloudfoundry-incubator/uaago#5]
`NewClient` in `client.go` returns a struct, rather than an interface. This makes testing classes that use this library more difficult. Switching to returning an interface with `GetAuthToken`, `GetAuthTokenWithExpiresIn`, and `TokenIsAuthorized` would help consumers of this library write tests in their own code.

**Comment by cholick** [comment]
Happy to PR this if someone gives a heads up that it would be accepted.

**Comment by poy** [comment]
I prefer the pattern where the consumer defines the interface and then the struct adheres to it. We use that in several places and I've seen some blogs that contend it being a strong practice (e.g. https://medium.com/@cep21/what-accept-interfaces-return-structs-means-in-go-2fe879e25ee8#.6rg0wgmaa).

However, I would be happy to see a use-case.

**Comment by cholick** [comment]
Fair enough; will refactor code on my side.
